# Generated by Django 4.1 on 2022-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('zipcode', models.CharField(max_length=12)),
            ],
        ),
    ]
