# Generated by Django 4.1 on 2022-08-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawuk_2', '0002_remove_services_address_remove_services_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
